server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/t?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 3000ms
      quiet-period: 2999ms
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.keac