server:
  port: 8080
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1/t?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 3000ms
      quiet-period: 2999ms
  redis:
    ###数据库索引（默认0
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        ###最大连接数（负数没有限制
        max-active: 8
        ###连接池最大阻塞等待时间（负数没有限制
        max-wait: -1
        ###最大空闲连接
        max-idle: 5
        ###最小空闲连接
        min-idle: 0
    ###连接超时时间
    timeout: 10000
  profiles:
    active: prd
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.keac.mappers
  base-packages: com.keac.mappers

